### ISSUE TITLE
Also change `AWS_REGION` region based on aws config profile

### ISSUE THREAD

**Issue by dennisroche** [jonscheiding/posh-awsp#1]
Thanks for building this great tool.

I would like to extend it to also change `AWS_REGION` environment variable based on the profile selected. 

e.g. in `.aws/config`

```
[profile region1]
region=ap-southeast-2
```

```
[profile region2]
region=us-east-1
```

Thoughts?

**Comment by jonscheiding** [comment]
@dennisroche Sorry for the delay responding, I didn't have notifications configured properly.

Interesting idea ... I'd have thought that setting `AWS_PROFILE` would generally take care of this, since tools that understand that variable will draw the region from the appropriate profile.  Can you expand on the use case?

**Comment by dennisroche** [comment]
> since tools that understand that variable will draw the region from the appropriate profile

that is correct, however i found it useful to be explicit and know the region that i am working in. 

one of the tools that doesn't have a deeper understanding of the profile is command prompt enhancements, e.g. https://starship.rs/ (see https://starship.rs/config/#aws). 

perhaps this is where idea came from but then i found it also useful to see the region displayed in the `awsp` list.

**Comment by jonscheiding** [comment]
@dennisroche 

Ok I think I understand the use case. I would be inclined to submit a PR to Starship to make it pull from the profile instead of the environment variable as applicable, but I have no idea whether that's feasible or whether they would accept it, so your proposed workaround here makes sense to me. I'll merge your PR and push a new version once I have a chance to test it out locally.

Thanks for submitting!

**Comment by dennisroche** [comment]
I'll try to submit a PR to Starship if only to do some `rustlang`. 😄 It has been discussed in https://github.com/starship/starship/issues/443 but not implemented, instead preferring env variables.

We can make setting the actual environment variable optional; displaying the environment variable in the profile name is useful. 

Shout if you have any issues; I've been running this branch locally for months now.

**Comment by dennisroche** [comment]
**Update** it looks like it is now supported https://github.com/starship/starship/blob/77bd80839ef6ac94cbf8e95095c566afd4f9b499/src/modules/aws.rs#L15

--- 
As it supported by Starship would you like to keep the changes to display the region in the profile selection?
